version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"  # Expose the Spring Boot app on port 8081 on the host
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/springbootmvcsdpproject11  # DB hostname is 'db' as per Docker Compose service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=springbootmvcsdpproject11
    ports:
      - "3306:3306"  # Expose MySQL database port on host (so you can access MySQL directly if needed)
